package com.omni_me.app

import android.content.Intent
import android.net.Uri
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.view.View
import android.view.ViewGroup
import android.webkit.WebView
import androidx.activity.enableEdgeToEdge
import androidx.core.content.FileProvider
import org.json.JSONObject
import java.io.File
import java.io.FileOutputStream

/*
 * Phase 3.3: receive shared receipts/statements from other Android apps.
 *
 * Tauri's stock MainActivity just hands `onCreate` to TauriActivity, which
 * starts the WebView. We extend it to also catch SEND intents — when the
 * user shares a file into Omni-Me from Gallery/Drive/Gmail, we stash the
 * bytes plus a small metadata sidecar inside the app's private filesDir.
 * The WASM frontend pulls the pair on mount via the
 * `take_pending_share_intent` Tauri command and routes into the capture
 * flow with the bytes pre-loaded.
 *
 * Why side-files rather than a JNI callback: keeps the Kotlin↔Rust contract
 * dirt-simple (Rust just reads two files) and survives the case where the
 * intent fires before the WebView is ready to receive events.
 */
class MainActivity : TauriActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        enableEdgeToEdge()
        // Chrome DevTools remote inspection, gated on a BUILD-TIME flag.
        //
        // This cannot key off the build profile: Tauri only enables DevTools
        // for --debug, but Android must be built --release (a debug build bakes
        // in the dev URL via cfg!(debug_assertions)), so BuildConfig.DEBUG is
        // always false here and would remove the capability entirely.
        //
        // It also must not be unconditional, which is what it used to be: on a
        // release APK, adb shell cannot read app-private data, but an attached
        // DevTools session can invoke the entire __TAURI__ command surface —
        // every journal entry, wipe_all_data, set_llm_config. That turns brief
        // adb access into total access.
        //
        // So: keep the capability, gate the trigger. Build with
        // OMNI_WEBVIEW_DEBUG=1 when you intend to debug on-device (BUILD.md);
        // shipped builds leave it unset. DevFlags.kt is generated by
        // src-tauri/build.rs.
        if (DevFlags.WEBVIEW_DEBUG) {
            WebView.setWebContentsDebuggingEnabled(true)
        }
        super.onCreate(savedInstanceState)
        intent?.let { handleSendIntent(it) }
        // Bridge Android's system-bar insets into CSS custom properties so
        // the frontend can `padding-bottom: var(--safe-area-inset-bottom)`.
        // Implementation lives in `InsetBridge.kt` (same override pattern as
        // this file — see `build.rs::apply_android_overrides`).
        InsetBridge.install(this)
    }

    /*
     * Paint the WebView's canvas charcoal before it loads anything.
     *
     * `res/values/themes.xml` covers launcher-tap → WebView-attach, but the
     * instant the WebView paints, what shows is the *document's* canvas — and
     * the served `index.html` is generated by dx with no stylesheet link and no
     * background of its own (Tailwind is injected later by the wasm bundle).
     * Chromium's default canvas is white, so a cold boot flashed full white
     * between the charcoal window and the splash: measured on-device at ~300ms,
     * reproducibly, on every tab.
     *
     * `setBackgroundColor` changes that canvas colour — the same call used to
     * make a WebView transparent — so an unstyled document paints charcoal
     * rather than white. Keep the hex equal to `--color-bg` and to themes.xml;
     * all three exist so the whole launch is one continuous colour.
     *
     * `onWebViewCreate` is wry's own hook (`WryActivity.setWebView` calls it at
     * creation, before the first load), which is the earliest moment the view
     * exists — doing this from `onCreate` would be too early to find it.
     */
    override fun onWebViewCreate(webView: WebView) {
        webView.setBackgroundColor(BACKGROUND_COLOR)
    }

    override fun onNewIntent(intent: Intent) {
        super.onNewIntent(intent)
        handleSendIntent(intent)
    }

    // --- Hardware/gesture back → in-app navigation (#372) ---
    //
    // Stock Tauri lets the back button finish the activity, so a back press from
    // anywhere in the app closes it — even when the user only meant to leave a
    // Finances drill-down or a note (the on-screen Back is often out of thumb
    // reach on a phone). Instead we consult the web layer: the frontend keeps
    // `window.__omniCanGoBack` current on every nav change (see `bridge.rs` /
    // `main.rs` #372). If it can go back in-app, we dispatch `omni:back` and let
    // Dioxus pop one level; otherwise we background the app (moveTaskToBack)
    // rather than destroy the activity — the standard root-back behavior, and it
    // keeps the app warm so we dodge the cold-open cost (cf. #370).
    //
    // `onBackPressed()` is deprecated on API 33+ in favor of
    // OnBackPressedDispatcher / predictive back, but our target device is API 29
    // and the manifest doesn't opt into `enableOnBackInvokedCallback`, so the
    // legacy path still runs everywhere we ship. Migrate if/when we adopt
    // predictive back.
    @Deprecated("Legacy back handling; fine until we adopt predictive back (API 33+).")
    override fun onBackPressed() {
        val webView = findWebView(findViewById(android.R.id.content))
        if (webView == null) {
            @Suppress("DEPRECATION")
            super.onBackPressed()
            return
        }
        // `evaluateJavascript` and its callback both run on the UI thread; the
        // result is the JSON-serialized expression value ("true"/"false").
        webView.evaluateJavascript("window.__omniCanGoBack === true") { result ->
            if (result == "true") {
                webView.evaluateJavascript("window.dispatchEvent(new Event('omni:back'))", null)
            } else {
                moveTaskToBack(true)
            }
        }
    }

    private fun findWebView(view: View?): WebView? {
        if (view == null) return null
        if (view is WebView) return view
        if (view is ViewGroup) {
            for (i in 0 until view.childCount) {
                findWebView(view.getChildAt(i))?.let { return it }
            }
        }
        return null
    }

    // --- OTA install bridge (app-delivery) ---
    //
    // The in-app updater downloads + sha256-verifies a new APK (Rust
    // `download_android_update`) into the cache dir, then `request_android_install`
    // writes the APK path to a `filesDir/install_request` side-file. We poll that
    // file while foregrounded and, when it appears, launch the system package
    // installer for it. Side-file (not a JS interface) keeps the Kotlin↔Rust
    // contract dirt-simple and dodges the "injected object needs a page reload"
    // trap — same rationale as the share handler above.
    //
    // Installing OVER the existing app requires the new APK be signed with the
    // SAME release key (the keystore CI signs with); a debug-keystore build is
    // rejected by the installer. Android prompts once for "install unknown apps".

    private val installHandler = Handler(Looper.getMainLooper())
    private val installPoll = object : Runnable {
        override fun run() {
            checkInstallRequest()
            installHandler.postDelayed(this, INSTALL_POLL_MS)
        }
    }

    override fun onResume() {
        super.onResume()
        installHandler.removeCallbacks(installPoll)
        installHandler.postDelayed(installPoll, INSTALL_POLL_MS)
    }

    override fun onPause() {
        super.onPause()
        installHandler.removeCallbacks(installPoll)
    }

    /// Directory shared with the Rust side for the side-file channels.
    ///
    /// **This MUST match what Tauri's `app_local_data_dir()` returns**, because
    /// that is what `commands/update.rs` and `commands/share_intent.rs` use.
    /// Tauri resolves it via `PathPlugin.getDataDir` → **`activity.dataDir`**
    /// (`/data/user/0/<pkg>`), NOT `filesDir` (`/data/user/0/<pkg>/files`).
    ///
    /// Both channels previously used `filesDir` here, so Rust wrote to one
    /// directory and Kotlin read from another. The install poller simply never
    /// found the request and returned silently — the OTA update downloaded and
    /// sha256-verified, the UI said "Follow the system prompt", and then nothing
    /// happened, with no exception and no log line (found on-device 2026-08-31,
    /// v1.0.1). A comment in `share_intent.rs` asserted the two were the same
    /// directory; that was simply wrong.
    private fun bridgeDir(): File = dataDir

    private fun checkInstallRequest() {
        // Single location, deliberately. An earlier draft of this fix also
        // checked `filesDir` as a "legacy fallback", but the Rust side has
        // written this file to `app_local_data_dir()` (= `dataDir`) since the
        // OTA feature landed and never once wrote to `filesDir` — so that
        // branch was unreachable, and its comment claimed a history that did
        // not exist. Only the READER was ever on the wrong path. A plausible
        // comment covering dead code is exactly what caused this bug in the
        // first place; two are not better than one.
        val req = File(bridgeDir(), INSTALL_REQUEST_FILE)
        if (!req.exists()) return
        android.util.Log.i("OmniMe", "install request found at ${req.absolutePath}")
        val apkPath = try {
            req.readText().trim()
        } catch (e: Exception) {
            req.delete()
            return
        }
        req.delete()
        if (apkPath.isEmpty()) return
        try {
            val uri: Uri =
                FileProvider.getUriForFile(this, "$packageName.fileprovider", File(apkPath))
            val intent = Intent(Intent.ACTION_VIEW).apply {
                setDataAndType(uri, "application/vnd.android.package-archive")
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_ACTIVITY_NEW_TASK)
            }
            startActivity(intent)
            android.util.Log.i("OmniMe", "install intent fired for $apkPath")
        } catch (e: Exception) {
            android.util.Log.w("OmniMe", "install intent failed for $apkPath", e)
        }
    }

    private fun handleSendIntent(intent: Intent) {
        if (intent.action != Intent.ACTION_SEND) return
        val uri: Uri = intent.getParcelableExtra(Intent.EXTRA_STREAM) ?: return
        val mime = intent.type ?: contentResolver.getType(uri) ?: "application/octet-stream"

        try {
            // `bridgeDir()`, not `filesDir` — same fix as the install poller.
            // `share_intent.rs` reads `app_local_data_dir()` (= `dataDir`), so
            // writing to `filesDir` here left every shared file somewhere the
            // Rust side never looked.
            val bytesFile = File(bridgeDir(), SHARE_BYTES_FILE)
            contentResolver.openInputStream(uri)?.use { input ->
                FileOutputStream(bytesFile).use { output -> input.copyTo(output) }
            } ?: return

            val filename = queryDisplayName(uri) ?: bytesFile.name
            val meta = JSONObject().apply {
                put("mime", mime)
                put("filename", filename)
                put("size", bytesFile.length())
            }
            File(bridgeDir(), SHARE_META_FILE).writeText(meta.toString())
            android.util.Log.i("OmniMe", "share captured to ${bytesFile.absolutePath} ($mime)")
        } catch (e: Exception) {
            android.util.Log.w("OmniMe", "share intent capture failed", e)
        }
    }

    private fun queryDisplayName(uri: Uri): String? {
        return try {
            contentResolver.query(uri, null, null, null, null)?.use { cursor ->
                val idx = cursor.getColumnIndex(android.provider.OpenableColumns.DISPLAY_NAME)
                if (idx >= 0 && cursor.moveToFirst()) cursor.getString(idx) else null
            }
        } catch (_: Exception) {
            null
        }
    }

    companion object {
        // Must equal `android:windowBackground` in res/values/themes.xml and
        // `--color-bg` in frontend/input.css.
        const val BACKGROUND_COLOR = 0xFF1E1E1E.toInt()
        const val SHARE_BYTES_FILE = "share_intent.bin"
        const val SHARE_META_FILE = "share_intent.json"
        // Must match `INSTALL_REQUEST_FILE` in commands/update.rs.
        const val INSTALL_REQUEST_FILE = "install_request"
        const val INSTALL_POLL_MS = 1500L
    }
}
