use async_trait::async_trait;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use surrealdb::types::SurrealValue;
use std::fmt;

use crate::db::Database;

/// Error type for event store operations.
#[derive(Debug)]
pub enum EventError {
    Store(String),
    Validation(String),
    Projection(String),
}

impl fmt::Display for EventError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            EventError::Store(msg) => write!(f, "event store error: {msg}"),
            EventError::Validation(msg) => write!(f, "event validation error: {msg}"),
            EventError::Projection(msg) => write!(f, "projection error: {msg}"),
        }
    }
}

impl std::error::Error for EventError {}

impl From<surrealdb::Error> for EventError {
    fn from(err: surrealdb::Error) -> Self {
        EventError::Store(err.to_string())
    }
}

/// A persisted event with a generated ID.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Event {
    pub id: String,
    pub event_type: String,
    pub aggregate_id: String,
    pub timestamp: DateTime<Utc>,
    pub device_id: String,
    pub payload: serde_json::Value,
}

/// An event to be appended — the ID is generated by the store.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewEvent {
    pub event_type: String,
    pub aggregate_id: String,
    pub timestamp: DateTime<Utc>,
    pub device_id: String,
    pub payload: serde_json::Value,
}

/// Event store trait — append-only event log.
#[async_trait]
pub trait EventStore: Send + Sync {
    /// Append a new event, generating a ULID for the id.
    async fn append(&self, event: NewEvent) -> Result<Event, EventError>;

    /// Get all events since a given timestamp, optionally excluding a specific device.
    async fn get_since(
        &self,
        since: DateTime<Utc>,
        exclude_device: Option<&str>,
    ) -> Result<Vec<Event>, EventError>;

    /// Get all events for a given aggregate, ordered by timestamp.
    async fn get_by_aggregate(&self, aggregate_id: &str) -> Result<Vec<Event>, EventError>;
}

/// SurrealDB-backed event store implementation.
#[derive(Clone)]
pub struct SurrealEventStore {
    db: Database,
}

impl SurrealEventStore {
    pub fn new(db: Database) -> Self {
        Self { db }
    }
}

#[async_trait]
impl EventStore for SurrealEventStore {
    async fn append(&self, event: NewEvent) -> Result<Event, EventError> {
        let id = ulid::Ulid::new().to_string();
        let ts_str = event.timestamp.to_rfc3339();

        self.db
            .query(
                "CREATE type::record('events', $id) CONTENT {
                    event_type: $event_type,
                    aggregate_id: $aggregate_id,
                    timestamp: type::datetime($timestamp),
                    device_id: $device_id,
                    payload: $payload
                }",
            )
            .bind(("id", id.clone()))
            .bind(("event_type", event.event_type.clone()))
            .bind(("aggregate_id", event.aggregate_id.clone()))
            .bind(("timestamp", ts_str))
            .bind(("device_id", event.device_id.clone()))
            .bind(("payload", event.payload.clone()))
            .await
            .map_err(|e| EventError::Store(e.to_string()))?;

        Ok(Event {
            id,
            event_type: event.event_type,
            aggregate_id: event.aggregate_id,
            timestamp: event.timestamp,
            device_id: event.device_id,
            payload: event.payload,
        })
    }

    async fn get_since(
        &self,
        since: DateTime<Utc>,
        exclude_device: Option<&str>,
    ) -> Result<Vec<Event>, EventError> {
        let since_str = since.to_rfc3339();
        let exclude = exclude_device.unwrap_or("").to_string();

        let query = match exclude_device {
            Some(_) => {
                "SELECT meta::id(id) AS eid, event_type, aggregate_id,
                        <string> timestamp AS ts, timestamp,
                        device_id, <string> payload AS payload_str
                 FROM events
                 WHERE timestamp > type::datetime($since) AND device_id != $exclude_device
                 ORDER BY timestamp ASC"
            }
            None => {
                "SELECT meta::id(id) AS eid, event_type, aggregate_id,
                        <string> timestamp AS ts, timestamp,
                        device_id, <string> payload AS payload_str
                 FROM events
                 WHERE timestamp > type::datetime($since)
                 ORDER BY timestamp ASC"
            }
        };

        let mut response = self
            .db
            .query(query)
            .bind(("since", since_str))
            .bind(("exclude_device", exclude))
            .await
            .map_err(|e| EventError::Store(e.to_string()))?;

        let rows: Vec<EventRow> = response
            .take(0)
            .map_err(|e| EventError::Store(e.to_string()))?;

        Ok(rows.into_iter().map(Event::from).collect())
    }

    async fn get_by_aggregate(&self, aggregate_id: &str) -> Result<Vec<Event>, EventError> {
        let agg_id = aggregate_id.to_string();

        let mut response = self
            .db
            .query(
                "SELECT meta::id(id) AS eid, event_type, aggregate_id,
                        <string> timestamp AS ts, timestamp,
                        device_id, <string> payload AS payload_str
                 FROM events
                 WHERE aggregate_id = $aggregate_id
                 ORDER BY timestamp ASC",
            )
            .bind(("aggregate_id", agg_id))
            .await
            .map_err(|e| EventError::Store(e.to_string()))?;

        let rows: Vec<EventRow> = response
            .take(0)
            .map_err(|e| EventError::Store(e.to_string()))?;

        Ok(rows.into_iter().map(Event::from).collect())
    }
}

/// Internal row struct for SurrealQL query deserialization.
/// All fields are strings — timestamp and payload are cast to strings in the query.
#[derive(Debug, SurrealValue)]
struct EventRow {
    eid: String,
    event_type: String,
    aggregate_id: String,
    ts: String,
    device_id: String,
    payload_str: String,
}

impl From<EventRow> for Event {
    fn from(row: EventRow) -> Self {
        let timestamp = DateTime::parse_from_rfc3339(&row.ts)
            .map(|dt| dt.with_timezone(&Utc))
            .unwrap_or_else(|_| Utc::now());

        // SurrealDB's <string> cast on an object produces a format like:
        // "{ key: value }" which may not be valid JSON.
        // Try parsing as JSON, falling back to wrapping in an object.
        let payload = parse_surreal_object_string(&row.payload_str);

        Event {
            id: row.eid,
            event_type: row.event_type,
            aggregate_id: row.aggregate_id,
            timestamp,
            device_id: row.device_id,
            payload,
        }
    }
}

/// Parse a SurrealDB object string representation into serde_json::Value.
/// SurrealDB's <string> cast on objects produces SurrealQL syntax like:
/// `{ key: 'value', num: 42 }` which is NOT valid JSON.
/// We convert it by trying JSON first, then using a simple heuristic.
fn parse_surreal_object_string(s: &str) -> serde_json::Value {
    // Try standard JSON first
    if let Ok(val) = serde_json::from_str(s) {
        return val;
    }

    // SurrealDB object string format: { key: 'value', key2: 42 }
    // Convert single quotes to double quotes and unquoted keys to quoted
    let converted = convert_surreal_to_json(s);
    serde_json::from_str(&converted).unwrap_or(serde_json::Value::Null)
}

/// Best-effort conversion of SurrealDB object string to JSON.
fn convert_surreal_to_json(s: &str) -> String {
    let s = s.trim();
    if !s.starts_with('{') || !s.ends_with('}') {
        return format!("\"{}\"", s.replace('"', "\\\""));
    }

    let inner = &s[1..s.len() - 1];
    let mut result = String::from("{");
    let mut in_string = false;
    let mut string_char = ' ';
    let mut chars = inner.chars().peekable();
    let mut prev_was_colon = false;
    let mut key_start = true;

    while let Some(c) = chars.next() {
        if in_string {
            if c == string_char {
                result.push('"');
                in_string = false;
            } else if c == '"' {
                result.push('\\');
                result.push('"');
            } else {
                result.push(c);
            }
            continue;
        }

        match c {
            '\'' => {
                in_string = true;
                string_char = '\'';
                result.push('"');
                key_start = false;
            }
            '"' => {
                in_string = true;
                string_char = '"';
                result.push('"');
                key_start = false;
            }
            ':' => {
                result.push(':');
                prev_was_colon = true;
                key_start = false;
            }
            ',' => {
                result.push(',');
                key_start = true;
                prev_was_colon = false;
            }
            ' ' | '\t' | '\n' => {
                result.push(c);
            }
            _ if key_start && c.is_alphanumeric() || (key_start && c == '_') => {
                // Unquoted key — collect it and wrap in quotes
                let mut key = String::new();
                key.push(c);
                while let Some(&next) = chars.peek() {
                    if next.is_alphanumeric() || next == '_' {
                        key.push(chars.next().unwrap());
                    } else {
                        break;
                    }
                }
                result.push('"');
                result.push_str(&key);
                result.push('"');
                key_start = false;
                prev_was_colon = false;
            }
            _ => {
                result.push(c);
                if prev_was_colon {
                    prev_was_colon = false;
                }
                key_start = false;
            }
        }
    }

    result.push('}');
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    async fn test_db() -> Database {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("test.db");
        let db = crate::db::connect(path.to_str().unwrap()).await.unwrap();
        std::mem::forget(dir);
        db
    }

    #[tokio::test]
    async fn append_and_retrieve_by_aggregate() {
        let db = test_db().await;
        let store = SurrealEventStore::new(db);

        let new_event = NewEvent {
            event_type: "note_created".into(),
            aggregate_id: "note-1".into(),
            timestamp: Utc::now(),
            device_id: "device-a".into(),
            payload: serde_json::json!({"raw_text": "hello", "date": "2026-03-27"}),
        };

        let event = store.append(new_event).await.unwrap();
        assert_eq!(event.event_type, "note_created");
        assert_eq!(event.aggregate_id, "note-1");
        assert!(!event.id.is_empty());

        let events = store.get_by_aggregate("note-1").await.unwrap();
        assert_eq!(events.len(), 1);
        assert_eq!(events[0].id, event.id);
        // Verify payload roundtrips
        assert_eq!(events[0].payload["raw_text"], "hello");
    }

    #[tokio::test]
    async fn get_since_filters_by_timestamp() {
        let db = test_db().await;
        let store = SurrealEventStore::new(db);

        let t1 = chrono::DateTime::parse_from_rfc3339("2026-01-01T00:00:00Z")
            .unwrap()
            .with_timezone(&Utc);
        let t2 = chrono::DateTime::parse_from_rfc3339("2026-06-01T00:00:00Z")
            .unwrap()
            .with_timezone(&Utc);

        store
            .append(NewEvent {
                event_type: "note_created".into(),
                aggregate_id: "n1".into(),
                timestamp: t1,
                device_id: "d1".into(),
                payload: serde_json::json!({"raw_text": "old", "date": "2026-01-01"}),
            })
            .await
            .unwrap();

        store
            .append(NewEvent {
                event_type: "note_created".into(),
                aggregate_id: "n2".into(),
                timestamp: t2,
                device_id: "d1".into(),
                payload: serde_json::json!({"raw_text": "new", "date": "2026-06-01"}),
            })
            .await
            .unwrap();

        let cutoff = chrono::DateTime::parse_from_rfc3339("2026-03-01T00:00:00Z")
            .unwrap()
            .with_timezone(&Utc);

        let events = store.get_since(cutoff, None).await.unwrap();
        assert_eq!(events.len(), 1);
        assert_eq!(events[0].aggregate_id, "n2");
    }

    #[tokio::test]
    async fn get_since_excludes_device() {
        let db = test_db().await;
        let store = SurrealEventStore::new(db);

        let ts = Utc::now();

        store
            .append(NewEvent {
                event_type: "note_created".into(),
                aggregate_id: "n1".into(),
                timestamp: ts,
                device_id: "device-a".into(),
                payload: serde_json::json!({"raw_text": "from A", "date": "2026-03-27"}),
            })
            .await
            .unwrap();

        store
            .append(NewEvent {
                event_type: "note_created".into(),
                aggregate_id: "n2".into(),
                timestamp: ts,
                device_id: "device-b".into(),
                payload: serde_json::json!({"raw_text": "from B", "date": "2026-03-27"}),
            })
            .await
            .unwrap();

        let early = ts - chrono::Duration::seconds(10);
        let events = store.get_since(early, Some("device-a")).await.unwrap();
        assert_eq!(events.len(), 1);
        assert_eq!(events[0].device_id, "device-b");
    }
}
