use std::path::Path;

fn main() {
    // `DEFAULT_SERVER_URL` reads this via `option_env!`; cargo doesn't track
    // env vars used by `option_env!`, so declare it here for local rebuilds.
    println!("cargo:rerun-if-env-changed=OMNI_DEFAULT_SERVER_URL");
    println!("cargo:rerun-if-env-changed=OMNI_WEBVIEW_DEBUG");
    apply_android_overrides();
    tauri_build::build();
}

/// Copy files from `android-overrides/` over the corresponding paths in
/// `gen/android/`. `gen/android/` is gitignored — Tauri regenerates it on
/// every `tauri android init`, which silently overwrites our customizations
/// (share-target intent-filter, MainActivity intent handler, etc.). Running
/// this on every cargo build guarantees the overrides are in place
/// whenever the Android project exists.
///
/// No-op on machines that haven't run `tauri android init` (desktop dev).
fn apply_android_overrides() {
    let crate_root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let gen_main = crate_root.join("gen/android/app/src/main");
    if !gen_main.exists() {
        return;
    }

    let overrides = crate_root.join("android-overrides");
    if !overrides.exists() {
        return;
    }

    let pairs: &[(&str, &str)] = &[
        ("AndroidManifest.xml", "AndroidManifest.xml"),
        (
            "java/com/omni_me/app/MainActivity.kt",
            "java/com/omni_me/app/MainActivity.kt",
        ),
        (
            "java/com/omni_me/app/InsetBridge.kt",
            "java/com/omni_me/app/InsetBridge.kt",
        ),
        ("res/xml/file_paths.xml", "res/xml/file_paths.xml"),
        // Charcoal `windowBackground` so the launcher→WebView gap isn't a white
        // flash. Both configurations, because the app is dark-only.
        ("res/values/themes.xml", "res/values/themes.xml"),
        ("res/values-night/themes.xml", "res/values-night/themes.xml"),
    ];

    generate_dev_flags(&gen_main);

    for (src_rel, dst_rel) in pairs {
        let src = overrides.join(src_rel);
        let dst = gen_main.join(dst_rel);
        if !src.exists() {
            continue;
        }
        // Cargo only re-runs build.rs when listed inputs change.
        println!("cargo:rerun-if-changed={}", src.display());

        if let Some(parent) = dst.parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        if let Err(e) = std::fs::copy(&src, &dst) {
            println!(
                "cargo:warning=failed to copy {} -> {}: {}",
                src.display(),
                dst.display(),
                e
            );
        }
    }
}

/// Emit `DevFlags.kt` — build-time constants MainActivity reads.
///
/// Currently just one: whether to enable Chrome DevTools remote inspection on
/// the WebView. That used to be a hardcoded `true`, deliberately, because Tauri
/// only enables it for `--debug` and Android is forced to `--release` (a debug
/// build bakes in the dev URL through `cfg!(debug_assertions)`). The cost was
/// that every shipped APK exposed `@webview_devtools_remote_<pid>` — and on a
/// release APK that socket is a genuine escalation, because `adb shell` cannot
/// otherwise read app-private data, while a DevTools session can invoke the
/// whole `__TAURI__` command surface.
///
/// So the capability is kept and the *trigger* is gated: set
/// `OMNI_WEBVIEW_DEBUG=1` for a build you intend to debug on-device (see
/// BUILD.md), and leave it unset for anything you ship.
///
/// Generated from `build.rs` rather than declared as a gradle
/// `buildConfigField` because `gen/android/` is gitignored and regenerated by
/// `tauri android init`, so a gradle edit would not survive; this reuses the
/// same override seam as the Kotlin files above.
fn generate_dev_flags(gen_main: &Path) {
    let enabled = std::env::var("OMNI_WEBVIEW_DEBUG")
        .map(|v| {
            let v = v.trim().to_ascii_lowercase();
            !v.is_empty() && v != "0" && v != "false"
        })
        .unwrap_or(false);

    let contents = format!(
        "package com.omni_me.app\n\n\
         // GENERATED by src-tauri/build.rs — do not edit.\n\
         // Set OMNI_WEBVIEW_DEBUG=1 at build time to enable WebView DevTools.\n\
         object DevFlags {{\n    const val WEBVIEW_DEBUG = {enabled}\n}}\n"
    );

    let dst = gen_main.join("java/com/omni_me/app/DevFlags.kt");
    if let Some(parent) = dst.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    // Only rewrite on change, so a no-op cargo build doesn't churn the Android
    // source tree and force a gradle recompile.
    if std::fs::read_to_string(&dst).ok().as_deref() != Some(contents.as_str())
        && let Err(e) = std::fs::write(&dst, &contents)
    {
        println!("cargo:warning=failed to write {}: {}", dst.display(), e);
    }
}
